config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#index'

  resource :pages, only: [] do
    member do
      get :polyphonic_touch_fulltext
      get :polyphonic_touch_short_abstract
      get :polyphonic_touch_long_abstract
      get :photos
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="canonical" href="https://www.andrewwright.eu" />
    <title>Andrew Wright</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="google-site-verification" content="3gowywK1e825da_8mt1PyfINCV0S5UAb1ZCZj9EQmj8" />

  </head>

  <body>
    <%= yield %>

  </body>
</html>

app/views/layouts/applicationbootstrap.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Andrewwrightnl" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Andrewwrightnl</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Link1", "/path1"  %></li>
            <li><%= link_to "Link2", "/path2"  %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2018</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pages/bio.hml.erb
bio.hml.erb

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
<h1>Andrew Wright - Concert Pianist</h1>
<!-- <p>PhD MM MM MBA</p> -->

<%= image_tag "Andrew_Wright_001_B&W_superlow", class: "pic" %>


<!-- <p>Leader, Educator, Researcher, Developer, Entrepreneur, Musician, EdTech enthusiast</p>

<p>
  <a href="https://www.linkedin.com/in/andrew-wright-3b82b0128/">LinkedIn Profile</a> &nbsp | &nbsp
  <a href="https://github.com/ajw400">Github Profile</a>
</p> -->


<h3>
<%= link_to "Publicity Photos", photos_pages_path %></h3>
<h3>Artistic Biography</h3>
<p>
  Beginning with his orchestral debut with the State Orchestra in Michoacán, Mexico, American pianist Andrew Wright has performed throughout Europe and many other places in the world. He has been featured in live performance on over a dozen radio and television broadcasts. His competition prizes include top prizes at the 2012 Vienna International Piano Competition, and the 2011 San Daniele International Piano Meeting.
</p>

<p>
  Since moving to the Netherlands in 2009, he  has  kept  an  active  concert  schedule  performing  in  venues such as the Concertgebouw in Amsterdam, Anton Philipszaal in The Hague and the Concertgebouw Vereniging Nijmegen. His performances have been recorded for broadcast by Radio 4, TV West, Radio West and the TV show Podium Klassiek. In 2011, he was soloist with the Royal Conservatoire Orchestra for the Hague Conservatoire’s Liszt Festival.
</p>

<p>
  As a performer of contemporary music, Andrew enjoys working with composers, and has given a number of premieres in solo, chamber music, and orchestral settings. He has performed as part of George Crumb’s 75th Birthday tour. Andrew has also performed at some of the most prestigious festivals in North America, such as Banff, Music Academy of the West, the International Musical Arts Institute, Kent/Blossom, and the TCU-Van Cliburn Piano Festival.
</p>

<p>
  Andrew's degrees include a PhD from Leiden University, a masters degree from the Royal Conservatoire of the Hague, where he studied with Naum Grubert, as well as a masters degree from Southern Methodist University, where he studied with Alfred Mouledous and Joaquín Achúcarro. He was Konrad Wolff- Ilse Bing Scholar at Wichita State University where he received a bachelors degree studying with Julie Bees. Other teachers included Peter Amstutz, Mario Quiroz Alcantara and Jerome Lowenthal.

<p>
  Besides his activity as a concert pianist and piano teacher, Andrew has several other musical interests, which he finds inspiring and challenging. Andrew studied organ with Ben van Oosten at Codarts  (Rotterdam), graduating with a bachelors degree in organ and a diploma in church music. As an organist, he has performed on the most important and largest organs of the Netherlands, such as those of the St. Bavo Basilica in Haarlem, the Laurenskerk in Rotterdam, the Nieuwe Kerk in Katwijk, and the Petruskerk in Leens. He is cantor-organist of the Koningkerk in Voorburg, where his multi-stylistic musical activities include children and seniors and everyone in between. Andrew studied orchestral conducting with Michael Palmer and Mark Laycock and choral conducting with Wiecher Mandemaker.
</p>
<h3>Research</h3>
<p>Current topic areas: Piano Pedagogy, Educational Technology in Applied Music, Embodied Cognition</p>
<p>Doctoral (PhD) dissertation, Leiden University, 2016</p>
<h5>The Polyphonic Touch: coarticulation and polyphonic expression in the performance of piano and organ music</h4>
<%= link_to "Short abstract", polyphonic_touch_short_abstract_pages_path %> &nbsp | &nbsp
<%= link_to "Long abstract", polyphonic_touch_long_abstract_pages_path %> &nbsp | &nbsp
<%= link_to "Fulltext", polyphonic_touch_fulltext_pages_path %>
</div>
</div>
</div>

app/views/pages/photos.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <%= link_to "Home", root_path %>
      <h1>Publicity Photos</h1>
      <h3>Andrew Wright</h3>
      <a href="#lowres">low resolution</a> &nbsp | &nbsp
      <a href="#highres">high resolution</a>
      <hr>
      <h4>Please always credit Feiko Koster</h4>
      <hr>

      <div id="lowres">
      <h2>Low Resolution</h2>
      <%= image_tag "Andrew Wright 001 LR", class: "pic" %>
      <%= image_tag "Andrew Wright 002 LR", class: "pic" %>
      <%= image_tag "Andrew Wright 003 LR", class: "pic" %>
      <%= image_tag "Andrew Wright 004 extra LR", class: "pic" %>
      </div>
      <hr>
      <div id="highres">
      <h2>High Resolution</h2>
      <%= image_tag "Andrew Wright 001", class: "pic" %>
      <%= image_tag "Andrew Wright 001 B&W", class: "pic" %>
      <%= image_tag "Andrew Wright 002", class: "pic" %>
      <%= image_tag "Andrew Wright 003", class: "pic" %>
      <%= image_tag "Andrew Wright 004 extra", class: "pic" %>
      </div>

    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <h3>Links</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
        <%= link_to "Home", root_path %>
    </div>
  </div>
</div>

app/views/pages/polyphonic_touch_fulltext.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <%= link_to "Home", root_path %>
      <h1>The Polyphonic Touch:  coarticulation and polyphonic expression in the performance of piano and organ music</h1>
      <h3>By Andrew Wright, Leiden University, 2016</h3>
      <hr>
      <h4>Fulltext</h4>
      <p>
        Access the fulltext for free from Leiden University's <a href="https://openaccess.leidenuniv.nl/handle/1887/41220">online repository</a> containing all documents related to my dissertation.
      </p>
      <p>
        Or, just <a href="https://openaccess.leidenuniv.nl/bitstream/handle/1887/41220/The%20Polyphonic%20Touch%20-%20Andrew%20Wright%20-%20PhD%20Dissertation_Final.pdf?sequence=2">click here</a> to go straight to the pdf.
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <h3>Links</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <p>
        <%= link_to "Short abstract", polyphonic_touch_short_abstract_pages_path %> &nbsp | &nbsp
        <%= link_to "Long abstract", polyphonic_touch_long_abstract_pages_path %>
      </p>
      <p>
        <%= link_to "Home", root_path %>
      </p>
    </div>
  </div>
</div>

app/views/pages/polyphonic_touch_long_abstract.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <%= link_to "Home", root_path %>
      <h1>The Polyphonic Touch:  coarticulation and polyphonic expression in the performance of piano and organ music</h1>
      <h3>By Andrew Wright, Leiden University, 2016</h3>
      <hr>
      <h4>Long Abstract</h4>
      <p>
        Performances of solo keyboard repertoire can sound more or less polyphonic
        depending on the performer’s use of divergence in expression. Rather than being a purely
        cerebral experience, this expressive divergence is situated in an ecological relationship
        between keyboard and player where the gestural dynamics of technique and musicianship
        overlap. Specific body schemata relating to expressive divergence are therefore
        foundational to the interpretive freedom of the performer in creating polyphonic
        expression, and feature transparently in the musical result. This dissertation theorises
        expressive divergence by examining the embodiment of single voices through the
        hierarchical structuring of coarticulation, and by showing how these multi-layered
        gestures combine in the polyphony of expression.
      </p>
      <p>
        First, polyphony is defined as a term and situated in the centre of a web of meaning
        formed by its interdisciplinary use as a metaphor, a use that describes responsiveness
        between subjective agents. The concept of polyphony is then applied to expression in
        performance. An important feature of single-player polyphony is shown to be embodiment,
        where each hand (or finger) has its own subjective agency. Reflection about this
        experience foregrounds the inner relations between thought, body movement, and sound,
        which leads to a discussion of musical gesture. Such gesture is shown to have a
        hierarchical structure created by coarticulation (the corporeal subsumption of smaller
        units of gesture into overarching continuities). Coarticulation depends not only on the
        musculoskeletal structure of the body, but also on acquired skills and habits (body
        schemata). It underlies a kind of thinking-through-movement, which embodies and creates
        musical structure in performance, and forms an essential part of instrument-specific legato
        playing.
      </p>
      <p>
        Because coarticulation allows for participation of the whole body in shaping
        individual voices, it follows that the simultaneous divergence of shape in polyphonic
        playing involves a certain embodied interaction between voices. The term polyphonic
        voicing is introduced to describe a quality of performance (rather than a quality of the
        work being performed) and is contrasted to monophonic and homophonic voicing. In
        order to investigate polyphonic voicing, this dissertation presents a series of experiments
        using layered recordings, which in turn provide a springboard for reflection about
        objectification, agency, spatiality and musical tension.
        Examples are given of exercises for developing polyphonic expression and its
        underlying body schemata. These are accompanied with a discussion of the reasons behind
        each exercise, giving models for readers to use in developing their own exercises. Finally, a
        recital program is presented, demonstrating how the use of polyphonic expression can
        function within a normal concert practice across various style periods and in repertoire
        ranging from simple to complex. In the conclusions, the ideas of the dissertation are once
        again contextualised in the broad interdisciplinary horizon of polyphony as a metaphor.
        Single-player polyphonic expression is shown to enact or demonstrate an inner experience
        of the plurality of subjective agency, an experience made possible by its embodied
        dimension.
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <h3>Links</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <p>
        <%= link_to "Short abstract", polyphonic_touch_short_abstract_pages_path %> &nbsp | &nbsp
        <%= link_to "Fulltext", polyphonic_touch_fulltext_pages_path %>
      </p>
      <p>
        <%= link_to "Home", root_path %>
      </p>
    </div>
  </div>
</div>

app/views/pages/polyphonic_touch_short_abstract.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <%= link_to "Home", root_path %>
      <h1>The Polyphonic Touch:  coarticulation and polyphonic expression in the performance of piano and organ music</h1>
      <h3>By Andrew Wright, Leiden University, 2016</h3>
      <hr>
      <h4>Short Abstract</h4>
      <p>
        Performances of solo keyboard repertoire can sound more or less polyphonic depending on the performer’s use of divergence in expression. Rather than being a purely cerebral experience, this expressive divergence is situated in an ecological relationship between keyboard and player where the gestural dynamics of technique and musicianship overlap. Specific body schemata relating to expressive divergence are therefore foundational to the interpretive freedom of the performer in creating polyphonic expression, and feature transparently in the musical result. This dissertation theorises expressive divergence by examining the embodiment of single voices through the hierarchical structuring of coarticulation, and by showing how these multi-layered gestures combine in the polyphony of expression. This performative view of polyphony is contextualised not only in musical practice, but also in the wider interdisciplinary use of polyphony as a metaphor. Single-player polyphonic expression is shown to enact or demonstrate an inner experience of the plurality of subjective agency, an experience made possible by its embodied dimension. Besides verbalising and theorising polyphonic expression, this dissertation provides experiments and exercises useful for developing such a practice, as well as examples of its application in concert
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <h3>Links</h3>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-6 col-centered text-center">
      <p>
        <%= link_to "Long abstract", polyphonic_touch_long_abstract_pages_path %> &nbsp | &nbsp
        <%= link_to "Fulltext", polyphonic_touch_fulltext_pages_path %>
      </p>
      <p>
        <%= link_to "Home", root_path %>
      </p>
    </div>
  </div>
</div>